[build]
  command = "next build"
  publish = ".next"

[build.environment]
  # These are placeholders. You must set these in the Netlify UI.
  NEXT_PUBLIC_FIREBASE_API_KEY="AIzaSyBcOqyzodvTQb0OZezrRCZB_vrAHrcW0zo"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="visaapply-21410.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID="visaapply-21410"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="visaapply-21410.firebasestorage.app"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="517653958537"
NEXT_PUBLIC_FIREBASE_APP_ID="1:517653958537:web:50c8cf754e7841b2acdb58"


[[plugins]]
  package = "@netlify/plugin-nextjs"
