[build]
  command = "next build"
  publish = ".next"

[build.environment]
  # These are placeholders. You must set these in the Netlify UI.
  NEXT_PUBLIC_FIREBASE_API_KEY = "YOUR_API_KEY_HERE"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "YOUR_AUTH_DOMAIN_HERE"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "YOUR_PROJECT_ID_HERE"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "YOUR_STORAGE_BUCKET_HERE"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "YOUR_SENDER_ID_HERE"
  NEXT_PUBLIC_FIREBASE_APP_ID = "YOUR_APP_ID_HERE"

[[plugins]]
  package = "@netlify/plugin-nextjs"
